apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: gt-pod
  name: gt-pod
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - while true;do date;sleep 10;done
    image: busybox
    name: gt-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
