apiVersion: v1
kind: Pod
metadata:
  name: gt-side-car-pod
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name:  common-volume
          mountPath:  /var/log/nginx
    - name: sidecar
      image: busybox
      command: ["sh","-c","while true; do echo hi; sleep 10; done"]
      volumeMounts:
        - name:  common-volume
          mountPath:  /var/log/nginx

  volumes:
    - name: common-volume
      emptyDir: {}